# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "base"

  if Vagrant.has_plugin?('vagrant-env')
    config.env.enable
  end

  config.nfs.functional = false

  config.vm.synced_folder "..", "/test", type: "rsync"

  if ENV['SHUTDOWN']
    config.vm.provision 'shell', inline: "sudo shutdown #{ENV['SHUTDOWN']}"
  end

  config.vm.provider :vmck do |vmck|
    vmck.image_path = 'imgbuild-master.qcow2.tar.gz'
    vmck.vmck_url = ENV['VMCK_URL']
    vmck.memory = 1024 * 2
    vmck.cpus = 1
  end
end
